import { makeStyles } from "@mui/styles"

export const useStyles = makeStyles({
  headerMain: {
    fontFamily: "Mulish",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "40px",
    lineHeight: "45px",
    alignItems: "center",
    textAlign: "center",
    color: "rgba(0, 0, 0, 0.65)",
    margin: "40px 0px 80px 0px",
  },
  subHeaders: {
    margin: "80px 0px 80px 0px",
    fontFamily: "Mulish",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "20px",
    lineHeight: "1.7px",
    alignItems: "center",
    color: " #02B468",
    letterSpacing: "2px",
    textTransform: "uppercase",
  },
  SearchOptionContainer: {
    marginTop: "150px",
  },
  MainContainer: {
    padding: "0px 50px",
  },
  searchBtn: {
    width: "200px",
    height: "40px",
    background: "#02B468",
    color: "#FFFFFF",
    borderStyle: "none",
    borderRadius: "5px",
    cursor: "pointer",
  },
  SelectChip: {
    width: "100%",
  },
  ListItemIcon: {
    color: " #02B468",
    marginTop: "10px",
  },
  ListItemText: {
    display: "inline-block",
  },
  SearchOptions: {
    display: "flex",
    margin: "0px 200px",
  },
  OptionBox: {
    width: "200px",
    height: "40px",
    marginRight: "10px",
  },
  searchContainer: {},
  searchForm: {
    display: "flex",
  },
  Input: {
    width: "500px",
    height: "40px",
    background: "rgba(196, 196, 196, 0.05)",
    border: "1px solid #02B468",
    boxSizing: "border-box",
    marginBottom: "10px",
    outline: "none",
    textIndent: "10px",
  },
  searchCategories: {
    width: "112px",
    height: "40px",
    background: "rgba(196, 196, 196, 0.05)",
    border: "1px solid #02B468",
    boxSizing: "border-box",
    borderTopLeftRadius: "100px",
    borderBottomLeftRadius: "100px",
    outline: "none",
    textIndent: "10px",
    cursor: "pointer",
  },
  searbBtn: {
    width: "110px",
    height: "40px",
    background: " #02B468",
    border: "1px solid #02B468",
    boxSizing: "border-box",
    borderTopRightRadius: "100px",
    borderBottomRightRadius: "100px",
    cursor: "pointer",
    color: "#ffffff",
  },
})
