export const SIGNUP__USER__START = "SIGNUP__USER__START"
export const SIGNUP__USER__SUCCESS = "SIGNUP__USER__SUCCESS"
export const SIGNUP__USER__FAILURE = "SIGNUP__USER__FAILURE"

export const LOGIN__USER__START = "LOGIN__USER__START"
export const LOGIN__USER__SUCCESS = "LOGIN__USER__SUCCESS"
export const LOGIN__USER__FAILURE = "LOGIN__USER__FAILURE"

export const LOGOUT__USER__START = "LOGOUT__USER__START"
export const LOGOUT__USER__SUCCESS = "LOGOUT__USER__SUCCESS"
export const LOGOUT__USER__FAILURE = "LOGOUT__USER__FAILURE"

export const GOOGLE__USER__START = "GOOGLE__USER__START"
export const GOOGLE__USER__SUCCESS = "GOOGLE__USER__SUCCESS"
export const GOOGLE__USER__FAILURE = "GOOGLE__USER__FAILURE"

export const CREATE__EVENT__START = "CREATE__EVENT__START"
export const CREATE__EVENT__SUCCESS = "CREATE__EVENT__SUCCESS"
export const CREATE__EVENT__FAILURE = "CREATE__EVENT__FAILURE"

export const UPDATE__EVENT__START = "UPDATE__EVENT__START"
export const UPDATE__EVENT__SUCCESS = "UPDATE__EVENT__SUCCESS"
export const UPDATE__EVENT__FAILURE = "UPDATE__EVENT__FAILURE"

export const DELETE__EVENT__START = "DELETE__EVENT__START"
export const DELETE__EVENT__SUCCESS = "DELETE__EVENT__SUCCESS"
export const DELETE__EVENT__FAILURE = "DELETE__EVENT__FAILURE"

export const CREATE__TICKET__START = "CREATE__TICKET__START"
export const CREATE__TICKET__SUCCESS = "CREATE__TICKET__SUCCESS"
export const CREATE__TICKET__FAILURE = "CREATE__TICKET__FAILURE"

export const UPDATE__TICKET__START = "UPDATE__TICKET__START"
export const UPDATE__TICKET__SUCCESS = "UPDATE__TICKET__SUCCESS"
export const UPDATE__TICKET__FAILURE = "UPDATE__TICKET__FAILURE"

export const DELETE__TICKET__START = "DELETE__TICKET__START"
export const DELETE__TICKET__SUCCESS = "DELETE__TICKET__SUCCESS"
export const DELETE__TICKET__FAILURE = "DELETE__TICKET__FAILURE"

export const CREATE__USER__START = "CREATE__USER__START"
export const CREATE__USER__SUCCESS = "CREATE__USER__SUCCESS"
export const CREATE__USER__FAILURE = "CREATE__USER__FAILURE"

export const UPDATE__USER__START = "UPDATE__USER__START"
export const UPDATE__USER__SUCCESS = "UPDATE__USER__SUCCESS"
export const UPDATE__USER__FAILURE = "UPDATE__USER__FAILURE"

export const DELETE__USER__START = "DELETE__USER__START"
export const DELETE__USER__SUCCESS = "DELETE__USER__SUCCESS"
export const DELETE__USER__FAILURE = "DELETE__USER__FAILURE"

export const APPROVE__EVENT__START = "APPROVE__EVENT__START"
export const APPROVE__EVENT__SUCCESS = "APPROVE__EVENT__SUCCESS"
export const APPROVE__EVENT__FAILURE = "APPROVE__EVENT__FAILURE"

export const REJECT__EVENT__START = "REJECT__EVENT__START"
export const REJECT__EVENT__SUCCESS = "REJECT__EVENT__SUCCESS"
export const REJECT__EVENT__FAILURE = "REJECT__EVENT__FAILURE"

export const TICKETS__SHOW__START = "TICKETS__SHOW__START"
export const TICKETS__SHOW__SUCCESS = "TICKETS__SHOW__SUCCESS"
export const TICKETS__SHOW__FAILURE = "TICKETS__SHOW__FAILURE"

export const APPLY__REFUND__START = "APPLY__REFUND__START"
export const APPLY__REFUND__SUCCESS = "APPLY__REFUND__SUCCESS"
export const APPLY__REFUND__FAILURE = "APPLY__REFUND__FAILURE"
