import { makeStyles } from "@mui/styles"

export const useStyles = makeStyles({
  background: {},
  sideBar: {
    backgroundColor: "#121212",
  },
  Icons: {
    color: "#0000000",
  },
  userTableIcons: {
    color: "#02B468",
    cursor: "pointer",
  },
  InnerIcon: {
    marginLeft: "0px",
  },
  labels: {
    color: "#000000",
  },
  toolBar: {
    backgroundColor: "#02B468",
  },
  createEvent: {
    borderRadius: "5px",
    boxShadow: "0px 2px 5px rgba(0,0,0,0.25)",
    background: "rgba(196, 196, 196, 0.05)",
    padding: "20px 0px 20px 200px",
  },
  Title: {
    fontSize: "20px",
    textAlign: "center",
    fontWeight: "400",
    color: "#02B468",
    textTransform: "uppercase",
    display: "block",
    margin: "5px 0px 20px 0px",
  },
  daysContainer: {
    display: "flex",
    alignContent: "space-between",
  },
  day: {
    borderStyle: "none",
    color: "#000000",
    width: "20%",
    background: "#FFFFFF",
    marginBottom: "20px",
    textAlign: "center",
  },
  form: {
    marginLeft: "360px",
    marginBottom: "50px",
  },
  Inputs: {
    border: "1px solid #333",
    width: "45%",
    height: "35px",
    background: "#FFFFFF",
    boxSizing: "border-box",
    borderRadius: "4px",
    marginBottom: "10px",
    outline: "none",
    textIndent: "10px",
    marginRight: "10px",
    color: "#000000",
  },
  InputTickets: {
    border: "1px solid #333",
    width: "100%",
    height: "35px",
    background: "#FFFFFF",
    boxSizing: "border-box",
    borderRadius: "4px",
    marginBottom: "10px",
    outline: "none",
    textIndent: "10px",
    marginRight: "10px",
    color: "#000000",
  },
  thumbnail: {
    border: "1px solid #333",
    // width: "30%",
    height: "35px",
    background: "#FFFFFF",
    boxSizing: "border-box",
    borderRadius: "4px",
    marginBottom: "10px",
    outline: "none",
    textIndent: "10px",
    color: "#000000",
  },
  speakers: {},
  SendBtn: {
    width: "20%",
    height: "40px",
    background: " #02B468",
    border: "1px solid #02B468",
    boxSizing: "border-box",
    borderRadius: "3px",
    cursor: "pointer",
    color: "#ffffff",
  },
  LogoutBtn: {
    width: "10%",
    height: "40px",
    background: " #FFFFFF",
    boxSizing: "border-box",
    borderRadius: "3px",
    cursor: "pointer",
    color: "#000000",
  },
  InputPartOne: {
    width: "45%",
    height: "35px",
    background: "#ffffff",
    border: "1px solid #555",
    boxSizing: "border-box",
    borderRadius: "4px",
    marginBottom: "10px",
    outline: "none",
    textIndent: "10px",
    marginRight: "10px",
    color: "#000000",
  },
  InputPartArea: {
    width: "45%",
    background: "#ffffff",
    border: "1px solid #555",
    boxSizing: "border-box",
    borderRadius: "4px",
    marginBottom: "10px",
    outline: "none",
    textIndent: "10px",
    marginRight: "10px",
    color: "#000000",
  },
  Container: {
    background: "rgba(196, 196, 196, 0.05)",
    boxShadow: "0px 2px 5px rgba(0,0,0,0.25)",
    padding: "20px",
  },
  eventScheduleContainer: {
    marginTop: "50px",
  },
  eventScheduleFields: {
    display: "flex",
    flexDirection: "column",
    marginBottom: "20px",
  },
})
